# Generated by Django 3.2.4 on 2021-06-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('materiales', models.CharField(max_length=100)),
            ],
        ),
    ]
