# Generated by Django 3.2.4 on 2021-07-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webRayoMakween', '0002_auto_20210701_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='descripcion',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajos',
            name='materiales',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
