# Generated by Django 3.2.4 on 2021-07-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webRayoMakween', '0004_auto_20210701_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='descripcion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajos',
            name='materiales',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
